;; ALL AOT01 spectra done with pipeline 10 reduction
mr_p10 = n_elements(mr_p10) EQ 0
 IF mr_p10 THEN AFGL190         = read_faar('$DATA/AFGL190/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2155        = read_faar('$DATA/AFGL2155/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2233        = read_faar('$DATA/AFGL2233/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2256        = read_faar('$DATA/AFGL2256/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2310        = read_faar('$DATA/AFGL2310/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2392        = read_faar('$DATA/AFGL2392/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2477_1      = read_faar('$DATA/AFGL2477/rev526/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2477_2      = read_faar('$DATA/AFGL2477/rev561/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL2699        = read_faar('$DATA/AFGL2699/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL3068        = read_faar('$DATA/AFGL3068/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL3099        = read_faar('$DATA/AFGL3099/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL341         = read_faar('$DATA/AFGL341/OLP10/myrebin.fits')
 IF mr_p10 THEN AFGL5625        = read_faar('$DATA/AFGL5625/OLP10/myrebin.fits')
 IF mr_p10 THEN CD_49_11554     = read_faar('$DATA/CD_49_11554/OLP10/myrebin.fits')
 IF mr_p10 THEN CRL2688         = read_faar('$DATA/CRL2688/OLP10/myrebin.fits')
 IF mr_p10 THEN CRL618          = read_faar('$DATA/CRL618/OLP10/myrebin.fits')
 IF mr_p10 THEN HB5             = read_faar('$DATA/HB5/OLP10/myrebin.fits')
 IF mr_p10 THEN HD187885        = read_faar('$DATA/HD187885/OLP10/myrebin.fits')
 IF mr_p10 THEN HD56126         = read_faar('$DATA/HD56126/OLP10/myrebin.fits')
 IF mr_p10 THEN IC418           = read_faar('$DATA/IC418/OLP10/myrebin.fits')
 IF mr_p10 THEN IC5117          = read_faar('$DATA/IC5117/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS01005_7910  = read_faar('$DATA/IRAS01005+7910/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS02229       = read_faar('$DATA/IRAS02229/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS03313       = read_faar('$DATA/IRAS03313/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS06238_0904  = read_faar('$DATA/IRAS06238+0904/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS06582       = read_faar('$DATA/IRAS06582/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS13416       = read_faar('$DATA/IRAS13416/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS16594       = read_faar('$DATA/IRAS16594/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS17262       = read_faar('$DATA/IRAS17262/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS17534       = read_faar('$DATA/IRAS17534/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS18240_1     = read_faar('$DATA/IRAS18240/rev134/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS18240_2     = read_faar('$DATA/IRAS18240/rev149/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS19584_2652  = read_faar('$DATA/IRAS19584+2652/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS20000       = read_faar('$DATA/IRAS20000/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS21318       = read_faar('$DATA/IRAS21318/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS21489_5301  = read_faar('$DATA/IRAS21489+5301/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS22303       = read_faar('$DATA/IRAS22303/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS22574_6609  = read_faar('$DATA/IRAS22574+6609/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS23304_1     = read_faar('$DATA/IRAS23304/rev085/OLP10/myrebin.fits')
 IF mr_p10 THEN IRAS23304_2     = read_faar('$DATA/IRAS23304/rev396/OLP10/myrebin.fits')
 IF mr_p10 THEN IRC_10216       = read_faar('$DATA/IRC_10216/OLP10/myrebin.fits')
 IF mr_p10 THEN IRC_20326       = read_faar('$DATA/IRC_20326/OLP10/myrebin.fits')
 IF mr_p10 THEN IRC_40540       = read_faar('$DATA/IRC_40540/OLP10/myrebin.fits')
 IF mr_p10 THEN IRC_50096       = read_faar('$DATA/IRC_50096/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC3918_1       = read_faar('$DATA/NGC3918/rev079/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC3918_2       = read_faar('$DATA/NGC3918/rev299/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC40_1         = read_faar('$DATA/NGC40/rev300/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC40_2         = read_faar('$DATA/NGC40/rev444/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC6826_1       = read_faar('$DATA/NGC6826/rev272/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC6826_2       = read_faar('$DATA/NGC6826/rev302/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC7027_1       = read_faar('$DATA/NGC7027/rev024/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC7027_2       = read_faar('$DATA/NGC7027/rev558/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC7027_3       = read_faar('$DATA/NGC7027/tdt23001256/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC7027_4       = read_faar('$DATA/NGC7027/tdt23001357/OLP10/myrebin.fits')
 IF mr_p10 THEN NGC7027_5       = read_faar('$DATA/NGC7027/tdt23001458/OLP10/myrebin.fits')
 IF mr_p10 THEN SAO34504_1      = read_faar('$DATA/SAO34504/rev263/OLP10/myrebin.fits')
 IF mr_p10 THEN SAO34504_2      = read_faar('$DATA/SAO34504/rev366/OLP10/myrebin.fits')
 IF mr_p10 THEN U_CAM           = read_faar('$DATA/U_CAM/OLP10/myrebin.fits')
 IF mr_p10 THEN V_CYG           = read_faar('$DATA/V_CYG/OLP10/myrebin.fits')

;; Now classify this shit
cstars=['AFGL190','AFGL2155','AFGL2233','AFGL2310','AFGL2392','AFGL2477_1','AFGL2477_2','AFGL2699','AFGL3068','AFGL3099','AFGL341','AFGL5625','IRAS03313','IRAS06238_0904','IRAS06582','IRAS17534','IRAS19584_2652','IRAS21318','IRAS22303','IRC_10216','IRC_20326','IRC_40540','IRC_50096','U_CAM','V_CYG']
pagbs=['AFGL2256','CD_49_11554','CRL2688','CRL618','HD187885','HD56126','IRAS01005_7910','IRAS02229','IRAS13416','IRAS16594','IRAS20000','IRAS21489_5301','IRAS22574_6609','IRAS23304_1','IRAS23304_2','SAO34504_1','SAO34504_2']
pns=['HB5','IC418','IC5117','IRAS17262','IRAS18240_1','IRAS18240_2','NGC3918_1','NGC3918_2','NGC40_1','NGC40_2','NGC6826_1','NGC6826_2','NGC7027_1','NGC7027_2','NGC7027_3','NGC7027_4','NGC7027_5']

cstars=sh_uniq(cstars)
pagbs=sh_uniq(pagbs)
pns=sh_uniq(pns)

all30 = [cstars,pagbs,pns]
